# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
python:
  - "3.6"
install:
  - export ENVIRONMENT_YML="environment.yml"
  - export CONDA_PYTHON_VERSION=3.7
  - echo "ENVIRONMENT_YML = $ENVIRONMENT_YML"
  - echo "TRAVIS_PYTHON_VERSION = $TRAVIS_PYTHON_VERSION"
  - echo "CONDA_PYTHON_VERSION = $CONDA_PYTHON_VERSION"
  - env
  - sudo apt-get update
  - sudo apt-get remove -y python-boto
  - sudo apt-get install -y libasound* build-essential gfortran libopenblas-dev liblapack-dev pandoc portaudio19-dev
  - if [ ! -d "$HOME/miniconda" ]; then if [ ! -f "miniconda.sh" ] ; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh ; fi ; bash miniconda.sh -b -f -p "$HOME/miniconda" ; fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - cp .condarc ~/.condarc
  - conda update -n base conda
  - hash -r  # refresh the hash table of commands (because we added conda to PATH)
  - echo "running-- conda env create -f $ENVIRONMENT_YML -n testenv python=$CONDA_PYTHON_VERSION"
  - travis_wait 30 conda env create -q -f $ENVIRONMENT_YML -n testenv python=$CONDA_PYTHON_VERSION
  - source activate testenv
  - conda install pip
  - conda install python-annoy
  - pip install -U PyScaffold
  - pip install -r requirements.txt
  - pip install -U -e .
  - python -c "import nltk; nltk.download('punkt')"
  - conda info -a
  - conda list
  - pip install codecov
  - source tests/travis_install.sh  # installs full Anaconda3 instead of miniconda! plus spacy etc
before_script:
  - git config --global user.email "understander+travis@totalgood.com"
  - git config --global user.name "Understander App on Travis"
script:
  - python setup.py test
after_success:
  # - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
  - bash < (curl -s https://codecov.io/bash)
  - codecov
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
