# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
python:
  - "3.6"
install:
  - source tests/travis_install.sh  # installs full Anaconda3 instead of miniconda! plus spacy etc
  - conda activate understander
  - which python
before_script:
  - git config --global user.email "understander+travis@totalgood.com"
  - git config --global user.name "Understander App on Travis"
script:
  - conda activate understander
  - which python
  - python --version
  - pip install --upgrade setuptools pip
  - python setup.py test
after_success:
  - codecov
  # - bash < (curl -s https://codecov.io/bash)
  # - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
  - travis-cleanup

cache:
  pip: true
  directories:
    - $HOME/miniconda
